name: common
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  app:
    path: ../app
  home:
    path: ../home
  order:
    path: ../order
  personal:
    path: ../personal
  provider: ^6.1.2
  fluro: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: Basteleur
      fonts:
        - asset: assets/fonts/Basteleur.ttf


  uses-material-design: true
